name = "lightbulb"
version = "0.0.1"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
description = "A library for creating LTI 1.3 Tools in Gleam"
licences = ["MIT"]
repository = { type = "github", user = "Simon-Initiative", repo = "lightbulb" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

# Modules that should be considered "internal" and will not be included in
# generated documentation. Note this currently only affects documentation;
# public types and functions defined in these modules are still public.
#
# Items in this list are "globs" that are matched against module names. See:
# https://docs.rs/glob/latest/glob/struct.Pattern.html
internal_modules = [
  "lightbulb/jwk",
  "lightbulb/utils/**",
  "lightbulb/providers/http_mock_provider",
  "lightbulb/providers/httpc_provider",
  "lightbulb/providers/memory_provider/tables",
  "lightbulb/jose",
]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
ids = ">= 0.14.0 and < 1.0.0"
birl = ">= 1.8.0 and < 2.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_httpc = ">= 4.1.1 and < 5.0.0"
gleam_json = ">= 3.0.1 and < 4.0.0"
jose = ">= 1.11.10 and < 2.0.0"
jsx = ">= 3.1.0 and < 4.0.0"
gleam_otp = ">= 0.16.1 and < 1.0.0"
gleam_erlang = ">= 0.34.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
